### ISSUE TITLE
Class EnumChatFormatting is missing

### ISSUE THREAD

**Issue by byJavaDev** [LabyHelp/LabyHelp#8]
I tried to open the language selection dropdown menu, as LabyMod suddenly crashed:
`java.lang.NoClassDefFoundError: net/minecraft/util/EnumChatFormatting
	at de.labyhelp.addon.LabyPlayer.<clinit>(LabyPlayer.java:21)`

Apparently the class EnumChatFormatting is missing. This could probably be caused by the obfuscation (the class itself is available in the minecraft source).

Workaround:
It would be possible to replace all the enum values with concrete strings (e.g. §e for yellow) (Set the encoding to UTF-8 in build.gradle via `compileJava.options.encoding = 'UTF-8'`).

(See pull request)

**Comment by byJavaDev** [comment]
Additional: The game can also crash randomly because of this (probably when trying to render some colored string)

**Comment by marvinhuelsmann** [comment]
It should be fixed in the latest version
